[project]
name = "vulcan-robotics"
version = "0.1.0"
description = "Robot code for team 36830C for the 2025-2026 season."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.ruff.lint]
ignore = ["F403", "F405"]

[dependency-groups]
dev = [
    "python-dotenv>=1.2.1",
    "ruff>=0.12.9",
    "windows-toasts>=1.3.1",
]
